all:	binary two_three splay avl rbt bheap time_test testing
	corebuild binary.native
	corebuild two_three.native
	corebuild splay.native
	corebuild avl.native
	corebuild rbt.native
	corebuild bheap.native
	corebuild time_test.native
	corebuild testing.native

binary:
	corebuild binary.native

two_three:
	corebuild two_three.native

splay:
	corebuild splay.native

avl:
	corebuild avl.native

rbt:
	corebuild rbt.native

bheap:
	corebuild bheap.native

time_test:
	corebuild time_test.native

testing: 
	corebuild testing.native

clean:
	rm -rf _build *.native


